import React from 'react'
import {
    Table,
    Thead,
    Tbody,
    Tfoot,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer,
  } from '@chakra-ui/react'
import "./cstyle.css"
export default function TableElements({value}) {
  return (
    <>
        <Tr>
            <Td>is_threat</Td> 
            <Td className={value?.is_threat === "true" ? "bad" : "good"}>
                <p>{value?.is_threat}</p>
            </Td> 
        </Tr>
        <Tr>
            <Td>duration</Td> 
            <Td>{value?.duration}</Td> 
        </Tr>
        <Tr>
            <Td>protocol_type</Td> 
            <Td>{value?.protocol_type}</Td> 
        </Tr>
        <Tr>
            <Td>service</Td> 
            <Td>{value?.service}</Td> 
        </Tr>
        <Tr>
            <Td>flag</Td> 
            <Td>{value?.flag}</Td> 
        </Tr>
        <Tr>
            <Td>src_bytes</Td> 
            <Td>{value?.src_bytes}</Td> 
        </Tr>
        <Tr>
            <Td>dst_bytes</Td> 
            <Td>{value?.dst_bytes}</Td> 
        </Tr>
        <Tr>
            <Td>land</Td> 
            <Td>{value?.land}</Td> 
        </Tr>
        <Tr>
            <Td>wrong_fragment</Td> 
            <Td>{value?.wrong_fragment}</Td> 
        </Tr>
        <Tr>
            <Td>urgent</Td> 
            <Td>{value?.urgent}</Td> 
        </Tr>
        <Tr>
            <Td>hot</Td> 
            <Td>{value?.hot}</Td> 
        </Tr>
        <Tr>
            <Td>num_failed_logins</Td> 
            <Td>{value?.num_failed_logins}</Td> 
        </Tr>
        <Tr>
            <Td>logged_in</Td> 
            <Td>{value?.logged_in}</Td> 
        </Tr>
        <Tr>
            <Td>num_compromised</Td> 
            <Td>{value?.num_compromised}</Td> 
        </Tr>
        <Tr>
            <Td>root_shell</Td> 
            <Td>{value?.root_shell}</Td> 
        </Tr>
        <Tr>
            <Td>su_attempted</Td> 
            <Td>{value?.su_attempted}</Td> 
        </Tr>
        <Tr>
            <Td>num_root</Td> 
            <Td>{value?.num_root}</Td> 
        </Tr>
        <Tr>
            <Td>num_file_creations</Td> 
            <Td>{value?.num_file_creations}</Td> 
        </Tr>
        <Tr>
            <Td>num_shells</Td> 
            <Td>{value?.num_shells}</Td> 
        </Tr>
        <Tr>
            <Td>num_access_files</Td> 
            <Td>{value?.num_access_files}</Td> 
        </Tr>
        <Tr>
            <Td>num_outbound_cmds</Td> 
            <Td>{value?.num_outbound_cmds}</Td> 
        </Tr>
        <Tr>
            <Td>is_host_login</Td> 
            <Td>{value?.is_host_login}</Td> 
        </Tr>
        <Tr>
            <Td>is_guest_login</Td> 
            <Td>{value?.is_guest_login}</Td> 
        </Tr>
        <Tr>
            <Td>count</Td> 
            <Td>{value?.count}</Td> 
        </Tr>
        <Tr>
            <Td>srv_count</Td> 
            <Td>{value?.srv_count}</Td> 
        </Tr>
        <Tr>
            <Td>serror_rate</Td> 
            <Td>{value?.serror_rate}</Td> 
        </Tr>
        <Tr>
            <Td>rerror_rate</Td> 
            <Td>{value?.rerror_rate}</Td> 
        </Tr>
        <Tr>
            <Td>srv_rerror_rate</Td> 
            <Td>{value?.srv_rerror_rate}</Td> 
        </Tr>
        <Tr>
            <Td>same_srv_rate</Td> 
            <Td>{value?.same_srv_rate}</Td> 
        </Tr>
        <Tr>
            <Td>diff_srv_rate</Td> 
            <Td>{value?.diff_srv_rate}</Td> 
        </Tr>
        <Tr>
            <Td>srv_diff_host_rate</Td> 
            <Td>{value?.srv_diff_host_rate}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_count</Td> 
            <Td>{value?.dst_host_count}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_srv_count</Td> 
            <Td>{value?.dst_host_srv_count}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_same_srv_rate</Td> 
            <Td>{value?.dst_host_same_srv_rate}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_diff_srv_rate</Td> 
            <Td>{value?.dst_host_diff_srv_rate}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_same_src_port_rate</Td> 
            <Td>{value?.dst_host_same_src_port_rate}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_srv_diff_host_rate</Td> 
            <Td>{value?.dst_host_srv_diff_host_rate}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_serror_rate</Td> 
            <Td>{value?.dst_host_serror_rate}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_srv_serror_rate</Td> 
            <Td>{value?.dst_host_srv_serror_rate}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_rerror_rate</Td> 
            <Td>{value?.dst_host_rerror_rate}</Td> 
        </Tr>
        <Tr>
            <Td>dst_host_srv_rerror_rate</Td> 
            <Td>{value?.dst_host_srv_rerror_rate}</Td> 
        </Tr>
        <Tr>
            <Td>label</Td> 
            <Td>{value?.label}</Td> 
        </Tr>
        <Tr>
            <Td>difficulty</Td> 
            <Td>{value?.difficulty}</Td> 
        </Tr>
        
    </>
  )
}
