# Generated by Django 4.2 on 2024-04-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lstm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lstm_neural_model",
            name="is_threat",
            field=models.BooleanField(default=False),
        ),
    ]
