# Generated by Django 4.2 on 2024-04-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lstm", "0002_lstm_neural_model_is_threat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lstm_neural_model",
            name="is_threat",
            field=models.CharField(max_length=255),
        ),
    ]
